export const STOPWORDS = new Set([
  "a", "acá", "ahí", "al", "algo", "algún", "alguna", "algunas", "alguno", "algunos", "allá",
  "allí", "ambos", "ante", "antes", "aquel", "aquella", "aquellas", "aquello", "aquellos",
  "aquí", "así", "aunque", "bajo", "bien", "cada", "casi", "como", "con", "contra", "cual",
  "cuales", "cualquier", "cualquiera", "cualquieras", "cuan", "cuando", "cuanta", "cuantas",
  "cuanto", "cuantos", "de", "dejar", "del", "demás", "dentro", "desde", "donde", "dos",
  "el", "él", "ella", "ellas", "ellos", "empleáis", "emplean", "emplear", "empleas", "empleo",
  "en", "encima", "entonces", "entre", "era", "erais", "éramos", "eran", "eras", "eres", "es",
  "esa", "esas", "ese", "eso", "esos", "esta", "estaba", "estabais", "estábamos", "estaban",
  "estabas", "estad", "estada", "estadas", "estado", "estados", "estáis", "estamos", "están",
  "estar", "estará", "estarán", "estarás", "estaré", "estaréis", "estaremos", "estaría",
  "estaríais", "estaríamos", "estarían", "estarías", "estas", "este", "esté", "estéis",
  "estemos", "estén", "estés", "esto", "estos", "estoy", "estuvo", "estuviera", "estuvierais",
  "estuviéramos", "estuvieran", "estuvieras", "estuvieron", "estuviese", "estuvieseis",
  "estuviésemos", "estuviesen", "estuvieses", "estuvimos", "estuviste", "estuvisteis",
  "estuviéramos", "estuvo", "ex", "excepto", "fuera", "fuerais", "fuéramos", "fueran", "fueras",
  "fueron", "fuese", "fueseis", "fuésemos", "fuesen", "fueses", "fui", "fuimos", "fuiste",
  "fuisteis", "ha", "habéis", "haber", "había", "habíais", "habíamos", "habían", "habías",
  "habida", "habidas", "habido", "habidos", "habiendo", "habrá", "habrán", "habrás", "habré",
  "habréis", "habremos", "habría", "habríais", "habríamos", "habrían", "habrías", "hace",
  "haceis", "hacemos", "hacen", "hacer", "haces", "hacia", "hago", "han", "has", "hasta",
  "hay", "haya", "hayáis", "hayamos", "hayan", "hayas", "he", "hemos", "hube", "hubiera",
  "hubierais", "hubiéramos", "hubieran", "hubieras", "hubieron", "hubiese", "hubieseis",
  "hubiésemos", "hubiesen", "hubieses", "hubimos", "hubiste", "hubisteis", "hubo", "la",
  "las", "le", "les", "lo", "los", "mas", "más", "me", "mi", "mis", "mía", "mías", "mientras",
  "mío", "míos", "misma", "mismas", "mismo", "mismos", "modo", "mucha", "muchas", "muchísima",
  "muchísimas", "muchísimo", "muchísimos", "mucho", "muchos", "muy", "nada", "ni", "ninguna",
  "ningunas", "ninguno", "ningunos", "no", "nos", "nosotras", "nosotros", "nuestra", "nuestras",
  "nuestro", "nuestros", "nunca", "os", "otra", "otras", "otro", "otros", "para", "pero",
  "poca", "pocas", "poco", "pocos", "podáis", "podamos", "poder", "podrá", "podrán", "podría",
  "podrían", "por", "por qué", "porque", "primero", "puede", "pueden", "puedo", "pues", "que",
  "qué", "quedó", "queremos", "quien", "quién", "quienes", "quienesquiera", "quienquiera",
  "quizá", "quizás", "sabe", "sabes", "se", "sea", "seáis", "seamos", "sean", "seas", "ser",
  "será", "serán", "serás", "seré", "seréis", "seremos", "sería", "seríais", "seríamos",
  "serían", "serías", "seáis", "si", "sí", "siempre", "siendo", "sin", "sino", "sois", "solamente",
  "solo", "somos", "soy", "su", "sus", "suya", "suyas", "suyo", "suyos", "sí", "tal", "también",
  "tampoco", "tan", "tanta", "tantas", "tanto", "tantos", "te", "tenéis", "tenemos", "tener",
  "tenga", "tengáis", "tengamos", "tengan", "tengas", "tengo", "tenido", "tenéis", "tenía",
  "teníais", "teníamos", "tenían", "tenías", "ti", "tiene", "tienen", "tienes", "todo", "todos",
  "tomó", "trabaja", "trabajais", "trabajamos", "trabajan", "trabajar", "trabajas", "trabajo",
  "tras", "tú", "tu", "tus", "tuve", "tuviera", "tuvierais", "tuviéramos", "tuvieran", "tuvieras",
  "tuvieron", "tuviese", "tuvieseis", "tuviésemos", "tuviesen", "tuvieses", "tuvimos",
  "tuviste", "tuvisteis", "tuvo", "tuya", "tuyas", "tuyo", "tuyos", "un", "una", "unas", "uno",
  "unos", "usa", "usais", "usamos", "usan", "usar", "usas", "uso", "usted", "ustedes", "va",
  "vais", "valor", "vamos", "van", "varias", "varios", "vaya", "veis", "ven", "ver", "verdad",
  "verdadera", "verdadero", "vez", "vosotras", "vosotros", "voy", "vuestra", "vuestras",
  "vuestro", "vuestros", "y", "ya", "yo"
]);
